version: '3.8'
services:
   db:
     image: mysql:5.7
     container_name: scrapingdb
     ports:
       - "3336:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: scraping
       MYSQL_USER: user
       MYSQL_PASSWORD: root

volumes:
  db_data: {}